[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "cd base",
    "pip install --upgrade pip",
    "pip install -e ."
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd base && python -m axiestudio run --host 0.0.0.0 --port $PORT --backend-only"

[variables]
PYTHONPATH = "/app/base"
AXIESTUDIO_HOST = "0.0.0.0"
AXIESTUDIO_BACKEND_ONLY = "true"
