/**
 * Default description for the flow
 * @constant
 */
export const DESCRIPTIONS: string[] = [
  "Kedja Orden, Bemästra Språket!",
  "Språkarkitekt i Arbete!",
  "Stärker Språkingenjörskonst.",
  "Skapa Språkförbindelser Här.",
  "Skapa, Anslut, Konversera.",
  "Smarta Kedjor, Smartare Konversationer.",
  "Bygger Broar mellan Prompter för Briljans.",
  "Språkmodeller, Frisläppta.",
  "Ditt Nav för Textgenerering.",
  "Promptly Genialiskt!",
  "Bygger Språkliga Labyrinter.",
  "Axie Studio: Skapa, Kedja, Kommunicera.",
  "Koppla Prickarna, Skapa Språk.",
  "Interaktiv Språkvävning.",
  "Generera, Innovera, Kommunicera.",
  "Konversationskatalysatormotor.",
  "Språkkedjemästare.",
  "Designa Dialoger med Axie Studio.",
  "Vårda NLP-Noder Här.",
  "Konversationskartografi Upplåst.",
  "Designa, Utveckla, Dialogisera.",
  "Frigör Språklig Kreativitet.",
  "Kartlägg Din Väg till Fantastiska Konversationer.",
  "Språkets Kraft vid Dina Fingertoppar.",
  "Skulptera Språk med Precision.",
  "Där Språk Möter Logik.",
  "Bygger Intelligenta Interaktioner.",
  "Ditt Pass till Språkliga Landskap.",
  "Skapa, Kurera, Kommunicera med Axie Studio.",
  "Flöda in i Språkets Framtid.",
  "Kartlägger Meningsfulla Konversationer.",
  "Reda ut Artikulationens Konst.",
  "Språkingenjörsexcellens.",
  "Navigera Konversationsnätverken.",
  "Skapa Konversationer, En Nod i Taget.",
  "Toppen av Promptgenerering.",
  "Språkmodeller, Kartlagda och Bemästrade.",
  "Kraftfulla Prompter, Perfekt Positionerade.",
  "Innovation i Interaktion med Axie Studio.",
  "Din Verktygslåda för Textgenerering.",
  "Utveckla Språkliga Möjligheter.",
  "Bygger Kraftfulla Lösningar med Språkmodeller.",
  "Upptäck Affärsmöjligheter med NLP.",
  "Utnyttja Kraften i Konversations-AI.",
  "Transformera Ditt Företag med Smarta Dialoger.",
  "Skapa Meningsfulla Interaktioner, Generera Värde.",
  "Frigör Affärspotential genom Språkingenjörskonst.",
  "Stärker Företag med Intelligenta Interaktioner.",
  "Driver Innovation i Företagskommunikation.",
  "Katalyserar Affärstillväxt genom Konversations-AI.",
  "Textgenerering Möter Affärstransformation.",
  "Navigera det Språkliga Landskapet, Upptäck Möjligheter.",
  "Skapa Kraftfulla Förbindelser, Öka Affärsvärde.",
  "Stärker Kommunikation, Möjliggör Tillfällen.",
  "Avancerad NLP för Banbrytande Affärslösningar.",
  "Innovation i Interaktion, Revolution i Intäkter.",
  "Maximera Påverkan med Intelligenta Konversationer.",
  "Bortom Textgenerering - Frigör Affärsmöjligheter.",
  "Lås upp AI:s Kraft i Dina Affärskonversationer.",
  "Skapa Dialoger som Driver Affärsframgång.",
  "Konstruerad för Excellens, Byggd för Affärer.",
];

/**
 * Adjectives for the name of the flow
 * @constant
 *
 */
export const ADJECTIVES: string[] = [
  "admiring",
  "adoring",
  "agitated",
  "amazing",
  "angry",
  "awesome",
  "backstabbing",
  "berserk",
  "big",
  "boring",
  "clever",
  "cocky",
  "compassionate",
  "condescending",
  "cranky",
  "desperate",
  "determined",
  "distracted",
  "dreamy",
  "drunk",
  "ecstatic",
  "elated",
  "elegant",
  "evil",
  "fervent",
  "focused",
  "furious",
  "gigantic",
  "gloomy",
  "goofy",
  "grave",
  "happy",
  "high",
  "hopeful",
  "hungry",
  "insane",
  "jolly",
  "jovial",
  "kickass",
  "lonely",
  "loving",
  "mad",
  "modest",
  "naughty",
  "nauseous",
  "nostalgic",
  "pedantic",
  "pensive",
  "prickly",
  "reverent",
  "romantic",
  "sad",
  "serene",
  "sharp",
  "sick",
  "silly",
  "sleepy",
  "small",
  "stoic",
  "stupefied",
  "suspicious",
  "tender",
  "thirsty",
  "tiny",
  "trusting",
  "bubbly",
  "charming",
  "cheerful",
  "comical",
  "dazzling",
  "delighted",
  "dynamic",
  "effervescent",
  "enthusiastic",
  "exuberant",
  "fluffy",
  "friendly",
  "funky",
  "giddy",
  "giggly",
  "gleeful",
  "goofy",
  "graceful",
  "grinning",
  "hilarious",
  "inquisitive",
  "joyous",
  "jubilant",
  "lively",
  "mirthful",
  "mischievous",
  "optimistic",
  "peppy",
  "perky",
  "playful",
  "quirky",
  "radiant",
  "sassy",
  "silly",
  "spirited",
  "sprightly",
  "twinkly",
  "upbeat",
  "vibrant",
  "witty",
  "zany",
  "zealous",
];
/**
 * Nouns for the name of the flow
 * @constant
 *
 */
export const NOUNS: string[] = [
  "albattani",
  "allen",
  "almeida",
  "archimedes",
  "ardinghelli",
  "aryabhata",
  "austin",
  "babbage",
  "banach",
  "bardeen",
  "bartik",
  "bassi",
  "bell",
  "bhabha",
  "bhaskara",
  "blackwell",
  "bohr",
  "booth",
  "borg",
  "bose",
  "boyd",
  "brahmagupta",
  "brattain",
  "brown",
  "carson",
  "chandrasekhar",
  "colden",
  "cori",
  "cray",
  "curie",
  "darwin",
  "davinci",
  "dijkstra",
  "dubinsky",
  "easley",
  "einstein",
  "elion",
  "engelbart",
  "euclid",
  "euler",
  "fermat",
  "fermi",
  "feynman",
  "franklin",
  "galileo",
  "gates",
  "goldberg",
  "goldstine",
  "goldwasser",
  "golick",
  "goodall",
  "hamilton",
  "hawking",
  "heisenberg",
  "heyrovsky",
  "hodgkin",
  "hoover",
  "hopper",
  "hugle",
  "hypatia",
  "jang",
  "jennings",
  "jepsen",
  "joliot",
  "jones",
  "kalam",
  "kare",
  "keller",
  "khorana",
  "kilby",
  "kirch",
  "knuth",
  "kowalevski",
  "lalande",
  "lamarr",
  "leakey",
  "leavitt",
  "lichterman",
  "liskov",
  "lovelace",
  "lumiere",
  "mahavira",
  "mayer",
  "mccarthy",
  "mcclintock",
  "mclean",
  "mcnulty",
  "meitner",
  "meninsky",
  "mestorf",
  "minsky",
  "mirzakhani",
  "morse",
  "murdock",
  "newton",
  "nobel",
  "noether",
  "northcutt",
  "noyce",
  "panini",
  "pare",
  "pasteur",
  "payne",
  "perlman",
  "pike",
  "poincare",
  "poitras",
  "ptolemy",
  "raman",
  "ramanujan",
  "ride",
  "ritchie",
  "roentgen",
  "rosalind",
  "saha",
  "sammet",
  "shaw",
  "shirley",
  "shockley",
  "sinoussi",
  "snyder",
  "spence",
  "stallman",
  "stonebraker",
  "swanson",
  "swartz",
  "swirles",
  "tesla",
  "thompson",
  "torvalds",
  "turing",
  "varahamihira",
  "visvesvaraya",
  "volhard",
  "wescoff",
  "williams",
  "wilson",
  "wing",
  "wozniak",
  "wright",
  "yalow",
  "yonath",
  "coulomb",
  "degrasse",
  "dewey",
  "edison",
  "eratosthenes",
  "faraday",
  "galton",
  "gauss",
  "herschel",
  "hubble",
  "joule",
  "kaku",
  "kepler",
  "khayyam",
  "lavoisier",
  "maxwell",
  "mendel",
  "mendeleev",
  "ohm",
  "pascal",
  "planck",
  "riemann",
  "schrodinger",
  "sagan",
  "tesla",
  "tyson",
  "volta",
  "watt",
  "weber",
  "wien",
  "zoBell",
  "zuse",
  "carroll",
];
